name: MLflow CI

on:
  push:
    branches:
      - main

jobs:

  train-model:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r MLProject/requirements.txt

      - name: Run Model Training
        run: |
          cd MLProject
          python modelling.py